language: php

php:
  - 5.3
  - 5.4

env:
  - CAKE_VERSION=master RUN_COVERAGE=no
  - CAKE_VERSION=2.4 RUN_COVERAGE=run
  - php /home/travis/.phpenv/versions/5.3.26/bin/composer.phar self-update  

before_script:
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - git clone git://github.com/simkimsia/UtilityLib plugins/UtilityLib
  - cp -R ../OpenGraphCake plugins/OpenGraphCake
  - chmod -R 777 ../cakephp/app/tmp
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'persistent' => false,
    );
    }" > ../cakephp/app/Config/database.php

script:
  - php plugins/OpenGraphCake/run-caketests.php $RUN_COVERAGE 5.4

notifications:
  email: false